
jobmanager.rpc.address: localhost
jobmanager.rpc.port: 6123

jobmanager.memory.process.size: 1600m
taskmanager.memory.process.size: 1728m

taskmanager.numberOfTaskSlots: 32

parallelism.default: 1

jobmanager.execution.failover-strategy: region

web.upload.dir: /Users/xin.hao/Downloads/flink-jars
