env.log.dir: /Users/xin.hao/Downloads/flink-logs

web.upload.dir: /Users/xin.hao/Downloads/flink-jars

state.backend: rocksdb
state.backend.incremental: true
state.checkpoints.dir: file:///Users/xin.hao/Downloads/flink-checkpoints

jobmanager.rpc.address: localhost
jobmanager.rpc.port: 6123

jobmanager.memory.process.size: 3800m
jobmanager.execution.failover-strategy: region

taskmanager.memory.process.size: 4000m
taskmanager.numberOfTaskSlots: 6
parallelism.default: 2
