env.log.dir: /Users/xin.hao/Downloads/flink-logs

web.upload.dir: /Users/xin.hao/Downloads/flink-jars

state.backend: filesystem
state.backend.incremental: true
state.checkpoints.dir: file:///Users/xin.hao/Downloads/flink-checkpoints
state.savepoints.dir: file:///Users/xin.hao/Downloads/flink-savepoints
state.backend.rocksdb.memory.managed: false

jobmanager.rpc.address: localhost
jobmanager.rpc.port: 6123

jobmanager.memory.process.size: 3800m
jobmanager.execution.failover-strategy: region

taskmanager.memory.process.size: 4000m
taskmanager.numberOfTaskSlots: 6
parallelism.default: 2

restart-strategy: none
