
jobmanager.rpc.address: localhost
jobmanager.rpc.port: 6123

jobmanager.memory.process.size: 3800m
taskmanager.memory.process.size: 4000m

taskmanager.numberOfTaskSlots: 6

parallelism.default: 1

jobmanager.execution.failover-strategy: region

web.upload.dir: /Users/xin.hao/Downloads/flink-jars
